export const galleryCategories = [
  "shutters",
  "shades",
  "blinds",
  "drapery",
] as const;

export type GalleryCategory = (typeof galleryCategories)[number];

export interface GalleryItem {
  src: string;
  alt: string;
  width: number;
  height: number;
  categories: GalleryCategory[];
}

export const galleryItems: GalleryItem[] = [
  { src: "/images/gallery/fauxwood-004-1200x850.jpg", alt: "FauxWood", width: 768, height: 544, categories: ["blinds"] },
  { src: "/images/gallery/norman-roller-shades-02.jpg", alt: "Norman roller shades", width: 768, height: 540, categories: ["shades"] },
  { src: "/images/gallery/plantation-shutters.jpg", alt: "Plantation Shutters", width: 768, height: 511, categories: ["shutters"] },
  { src: "/images/gallery/roman-shade-c.jpg", alt: "Roman Shade C", width: 768, height: 512, categories: ["shades"] },
  { src: "/images/gallery/roman-shade-a.jpg", alt: "Roman Shade A", width: 768, height: 590, categories: ["shades"] },
  { src: "/images/gallery/img-6800.jpg", alt: "IMG", width: 768, height: 512, categories: ["shades"] },
  { src: "/images/gallery/norman-roller-shades-01.jpg", alt: "Norman roller shades", width: 768, height: 583, categories: ["shades"] },
  { src: "/images/gallery/top-treatments-5.jpg", alt: "Top treatments (5)", width: 512, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/top-treatments-4.jpg", alt: "Top treatments (4)", width: 579, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/top-treatments-3.jpg", alt: "Top treatments (3)", width: 768, height: 512, categories: ["drapery"] },
  { src: "/images/gallery/top-treatments-2.jpg", alt: "Top treatments (2)", width: 576, height: 864, categories: ["drapery"] },
  { src: "/images/gallery/top-treatments-1.jpg", alt: "Top treatments (1)", width: 512, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/top-treatments-7.jpg", alt: "Top treatments (7)", width: 657, height: 565, categories: ["drapery"] },
  { src: "/images/gallery/breakfast-nook.jpg", alt: "Breakfast nook", width: 768, height: 703, categories: ["drapery"] },
  { src: "/images/gallery/drapery-14.jpg", alt: "Drapery (14)", width: 768, height: 514, categories: ["drapery"] },
  { src: "/images/gallery/drapery-13.jpg", alt: "Drapery (13)", width: 722, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/drapery-12.jpg", alt: "Drapery (12)", width: 469, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/drapery-11.jpg", alt: "Drapery (11)", width: 464, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/drapery-10.jpg", alt: "Drapery (10)", width: 512, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/drapery-9.jpg", alt: "Drapery (9)", width: 768, height: 511, categories: ["drapery"] },
  { src: "/images/gallery/drapery-8.jpg", alt: "Drapery (8)", width: 512, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/drapery-7.jpg", alt: "Drapery (7)", width: 475, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/drapery-6.jpg", alt: "Drapery (6)", width: 768, height: 504, categories: ["drapery"] },
  { src: "/images/gallery/drapery-5.jpg", alt: "Drapery (5)", width: 475, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/drapery-4.jpg", alt: "Drapery (4)", width: 768, height: 511, categories: ["drapery"] },
  { src: "/images/gallery/drapery-3.jpg", alt: "Drapery (3)", width: 800, height: 1097, categories: ["drapery"] },
  { src: "/images/gallery/drapery-2.jpg", alt: "Drapery (2)", width: 768, height: 263, categories: ["drapery"] },
  { src: "/images/gallery/drapery-1.jpg", alt: "Drapery (1)", width: 768, height: 539, categories: ["drapery"] },
  { src: "/images/gallery/drapery-20.jpg", alt: "Drapery (20)", width: 800, height: 800, categories: ["drapery"] },
  { src: "/images/gallery/drapery-19.jpg", alt: "Drapery (19)", width: 768, height: 538, categories: ["drapery"] },
  { src: "/images/gallery/drapery-17.jpg", alt: "Drapery (17)", width: 768, height: 537, categories: ["drapery"] },
  { src: "/images/gallery/drapery-18.jpg", alt: "Drapery (18)", width: 768, height: 512, categories: ["drapery"] },
  { src: "/images/gallery/drapery-15.jpg", alt: "Drapery (15)", width: 640, height: 998, categories: ["drapery"] },
  { src: "/images/gallery/flat-roman-shades-11.jpg", alt: "Flat Roman shades (11)", width: 768, height: 521, categories: ["shades"] },
  { src: "/images/gallery/renovation-and-expansion-of-1938-home.jpg", alt: "Renovation and Expansion of 1938 home", width: 576, height: 890, categories: ["shades"] },
  { src: "/images/gallery/flat-roman-shades-9.jpg", alt: "Flat Roman shades (9)", width: 390, height: 600, categories: ["drapery", "shades"] },
  { src: "/images/gallery/flat-roman-shades-8.jpg", alt: "Flat Roman shades (8)", width: 398, height: 600, categories: ["drapery", "shades"] },
  { src: "/images/gallery/flat-roman-shades-7.jpg", alt: "Flat Roman shades (7)", width: 689, height: 600, categories: ["shades"] },
  { src: "/images/gallery/flat-roman-shades-6.jpg", alt: "Flat Roman shades (6)", width: 512, height: 768, categories: ["shades"] },
  { src: "/images/gallery/flat-roman-shades-5.jpg", alt: "Flat Roman shades (5)", width: 512, height: 768, categories: ["drapery", "shades"] },
  { src: "/images/gallery/flat-roman-shades-4.jpg", alt: "Flat Roman shades (4)", width: 512, height: 768, categories: ["drapery"] },
  { src: "/images/gallery/flat-roman-shades-3.jpg", alt: "Flat Roman shades (3)", width: 536, height: 768, categories: ["shades"] },
  { src: "/images/gallery/flat-roman-shades-2.jpg", alt: "Flat Roman shades (2)", width: 768, height: 525, categories: ["shades"] },
  { src: "/images/gallery/flat-roman-shades-1.jpg", alt: "Flat Roman shades (1)", width: 768, height: 660, categories: ["shades"] },
  { src: "/images/gallery/flat-roman-shades-18.jpg", alt: "Flat Roman shades (18)", width: 768, height: 576, categories: ["shades"] },
  { src: "/images/gallery/flat-roman-shades-17.jpg", alt: "Flat Roman shades (17)", width: 768, height: 576, categories: ["shades"] },
  { src: "/images/gallery/light-grey-contemporary-kitchen.jpg", alt: "Light grey contemporary kitchen", width: 744, height: 592, categories: ["shades"] },
  { src: "/images/gallery/beautiful-living-room-interior-with-tall-vaulted-ceiling-loft-area-hardwood-floors-and-fireplace-in-new-luxury-home-has-large-bank-of-windows.jpg", alt: "Beautiful living room interior with tall vaulted ceiling, loft area, hardwood floors and fireplace in new luxury home. Has large bank of windows", width: 800, height: 639, categories: ["shades"] },
  { src: "/images/gallery/modern-wood-kitchen-with-table.jpg", alt: "Modern wood kitchen with table", width: 800, height: 646, categories: ["drapery", "shades"] },
  { src: "/images/gallery/aluminum-blinds-6.jpg", alt: "Aluminum blinds (6)", width: 706, height: 530, categories: ["blinds"] },
  { src: "/images/gallery/aluminum-blinds-5.jpg", alt: "Aluminum blinds (5)", width: 792, height: 594, categories: ["blinds"] },
  { src: "/images/gallery/aluminum-blinds-4.jpg", alt: "Aluminum blinds (4)", width: 676, height: 1152, categories: ["blinds"] },
  { src: "/images/gallery/aluminum-blinds-3.jpg", alt: "Aluminum blinds (3)", width: 768, height: 614, categories: ["blinds"] },
  { src: "/images/gallery/aluminum-blinds-2.jpg", alt: "Aluminum blinds (2)", width: 768, height: 614, categories: ["blinds"] },
  { src: "/images/gallery/aluminum-blinds-1.jpg", alt: "Aluminum blinds (1)", width: 800, height: 640, categories: ["blinds"] },
  { src: "/images/gallery/aluminum-blinds-7.jpg", alt: "Aluminum blinds (7)", width: 768, height: 453, categories: ["blinds"] },
  { src: "/images/gallery/faux-wood-blinds-5.jpg", alt: "Faux Wood Blinds (5)", width: 768, height: 576, categories: ["blinds"] },
  { src: "/images/gallery/faux-wood-blinds-4.jpg", alt: "Faux Wood Blinds (4)", width: 540, height: 400, categories: ["blinds"] },
  { src: "/images/gallery/faux-wood-blinds-3.jpg", alt: "Faux Wood Blinds (3)", width: 768, height: 512, categories: ["blinds"] },
  { src: "/images/gallery/faux-wood-blinds-2.jpg", alt: "Faux Wood Blinds (2)", width: 768, height: 544, categories: ["blinds"] },
  { src: "/images/gallery/faux-wood-blinds-1.jpg", alt: "Faux Wood Blinds (1)", width: 768, height: 544, categories: ["blinds"] },
  { src: "/images/gallery/faux-wood-blinds-7.jpg", alt: "Faux Wood Blinds (7)", width: 768, height: 576, categories: ["blinds"] },
  { src: "/images/gallery/wood-blinds-6.jpg", alt: "Wood Blinds (6)", width: 750, height: 964, categories: ["blinds"] },
  { src: "/images/gallery/wood-blinds-5.jpg", alt: "Wood Blinds (5)", width: 750, height: 963, categories: ["blinds"] },
  { src: "/images/gallery/wood-blinds-4.jpg", alt: "Wood Blinds (4)", width: 750, height: 1000, categories: ["blinds"] },
  { src: "/images/gallery/wood-blinds-3.jpg", alt: "Wood Blinds (3)", width: 750, height: 1000, categories: ["blinds"] },
  { src: "/images/gallery/wood-blinds-2.jpg", alt: "Wood Blinds (2)", width: 768, height: 576, categories: ["blinds"] },
  { src: "/images/gallery/studio-shutters-1.jpg", alt: "Studio shutters (1)", width: 500, height: 250, categories: ["shutters"] },
  { src: "/images/gallery/arched-shutters-1.jpg", alt: "Arched shutters (1)", width: 531, height: 531, categories: ["shutters"] },
  { src: "/images/gallery/arched-shutters-2.jpg", alt: "Arched shutters (2)", width: 768, height: 373, categories: ["shutters"] },
  { src: "/images/gallery/arched-shutters-3.jpg", alt: "Arched shutters (3)", width: 720, height: 960, categories: ["shutters"] },
  { src: "/images/gallery/arched-shutters-4.jpg", alt: "Arched shutters (4)", width: 768, height: 435, categories: ["shutters"] },
  { src: "/images/gallery/arched-shutters-5.jpg", alt: "Arched shutters (5)", width: 486, height: 486, categories: ["shutters"] },
  { src: "/images/gallery/arched-shutters-6.jpg", alt: "Arched shutters (6)", width: 640, height: 640, categories: ["shutters"] },
  { src: "/images/gallery/arched-shutters-7.jpg", alt: "Arched shutters (7)", width: 768, height: 576, categories: ["shutters"] },
  { src: "/images/gallery/ovation-wood-shutters-1.jpg", alt: "Ovation wood shutters (1)", width: 563, height: 795, categories: ["shutters"] },
  { src: "/images/gallery/ovation-wood-shutters-2.jpg", alt: "Ovation wood shutters (2)", width: 500, height: 500, categories: ["shutters"] },
  { src: "/images/gallery/plantation-shutters-page.jpg", alt: "Plantation Shutters Page", width: 768, height: 238, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-1.jpg", alt: "Polywood shutters (1)", width: 564, height: 564, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-2.jpg", alt: "Polywood shutters (2)", width: 700, height: 700, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-3.jpg", alt: "Polywood shutters (3)", width: 768, height: 435, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-4.jpg", alt: "Polywood shutters (4)", width: 770, height: 430, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-5.jpg", alt: "Polywood shutters (5)", width: 768, height: 576, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-6.jpg", alt: "Polywood shutters (6)", width: 620, height: 620, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-7.jpg", alt: "Polywood shutters (7)", width: 500, height: 250, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-8.jpg", alt: "Polywood shutters (8)", width: 768, height: 435, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-9.jpg", alt: "Polywood shutters (9)", width: 500, height: 250, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-10.jpg", alt: "Polywood shutters (10)", width: 640, height: 640, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-11.jpg", alt: "Polywood shutters (11)", width: 768, height: 435, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-12.jpg", alt: "Polywood shutters (12)", width: 725, height: 768, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-13.jpg", alt: "Polywood shutters (13)", width: 768, height: 739, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-14.jpg", alt: "Polywood shutters (14)", width: 768, height: 435, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-15.jpg", alt: "Polywood shutters (15)", width: 513, height: 513, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-16.jpg", alt: "Polywood shutters (16)", width: 534, height: 534, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-17.jpg", alt: "Polywood shutters (17)", width: 768, height: 768, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-18.jpg", alt: "Polywood shutters (18)", width: 614, height: 768, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-19.jpg", alt: "Polywood shutters (19)", width: 743, height: 559, categories: ["drapery", "shutters"] },
  { src: "/images/gallery/polywood-shutters-21.jpg", alt: "Polywood shutters (21)", width: 768, height: 544, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-22.jpg", alt: "Polywood shutters (22)", width: 768, height: 576, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-23.jpg", alt: "Polywood shutters (23)", width: 768, height: 576, categories: ["shutters"] },
  { src: "/images/gallery/polywood-shutters-24.jpg", alt: "Polywood shutters (24)", width: 768, height: 576, categories: ["shutters"] },
  { src: "/images/gallery/shutter-factory-1.jpg", alt: "Shutter factory (1)", width: 709, height: 768, categories: ["shutters"] },
  { src: "/images/gallery/shutter-factory-2.jpg", alt: "Shutter factory (2)", width: 800, height: 678, categories: ["shutters"] },
  { src: "/images/gallery/shutter-factory-3.jpg", alt: "Shutter factory (3)", width: 800, height: 678, categories: ["shutters"] },
  { src: "/images/gallery/shutter-factory-4.jpg", alt: "Shutter factory (4)", width: 798, height: 678, categories: ["shutters"] },
  { src: "/images/gallery/shutter-weather-stripping-1.jpg", alt: "Shutter weather stripping (1)", width: 500, height: 250, categories: ["shutters"] },
  { src: "/images/gallery/5-0-2.jpg", alt: "5.0.2", width: 500, height: 250, categories: ["shutters"] },
  { src: "/images/gallery/shutters-4.jpg", alt: "Shutters (4)", width: 640, height: 640, categories: ["shutters"] },
  { src: "/images/gallery/shutters-5.jpg", alt: "Shutters (5)", width: 768, height: 435, categories: ["shutters"] },
  { src: "/images/gallery/shutters-6.jpg", alt: "Shutters (6)", width: 564, height: 564, categories: ["shutters"] },
  { src: "/images/gallery/shutters-7.jpg", alt: "Shutters (7)", width: 640, height: 640, categories: ["shutters"] },
  { src: "/images/gallery/shutters-8.jpg", alt: "Shutters (8)", width: 480, height: 480, categories: ["shutters"] },
  { src: "/images/gallery/bypass-track-sliding-shutters-1.jpg", alt: "Bypass track sliding shutters (1)", width: 627, height: 627, categories: ["shutters"] },
  { src: "/images/gallery/bypass-track-sliding-shutters-2.jpg", alt: "Bypass track sliding shutters (2)", width: 354, height: 420, categories: ["shutters"] },
  { src: "/images/gallery/bypass-track-sliding-shutters-3.jpg", alt: "Bypass track sliding shutters (3)", width: 640, height: 640, categories: ["shutters"] },
  { src: "/images/gallery/bypass-track-sliding-shutters-4.jpg", alt: "Bypass track sliding shutters (4)", width: 768, height: 435, categories: ["shutters"] },
  { src: "/images/gallery/bypass-track-sliding-shutters-5.jpg", alt: "Bypass track sliding shutters (5)", width: 770, height: 500, categories: ["shutters"] },
  { src: "/images/gallery/drapery-install-1.jpg", alt: "Floral valance over sheer curtains in bathroom", width: 1050, height: 1400, categories: ["drapery"] },
  { src: "/images/gallery/drapery-install-2.jpg", alt: "Striped drapery with balloon shades on arched windows", width: 1400, height: 1050, categories: ["drapery"] },
  { src: "/images/gallery/drapery-install-3.jpg", alt: "Sheer panel track blinds lining a great room", width: 1400, height: 1050, categories: ["drapery"] },
  { src: "/images/gallery/drapery-install-4.jpg", alt: "Sheer curtains layered over living room windows", width: 1400, height: 1050, categories: ["drapery"] },
  { src: "/images/gallery/drapery-install-5.jpg", alt: "Floor-length drapery framing a two-story picture window", width: 1009, height: 1400, categories: ["drapery"] },
  { src: "/images/gallery/drapery-install-6.jpg", alt: "Layered drapery and sheers in a bedroom", width: 645, height: 1400, categories: ["drapery"] },
  { src: "/images/gallery/drapery-install-7.jpg", alt: "Ornate patterned drapery in a rotunda with chandelier", width: 1050, height: 1400, categories: ["drapery"] },
  { src: "/images/gallery/drapery-install-8.jpg", alt: "Close-up of pinch pleat drapery panels", width: 1050, height: 1400, categories: ["drapery"] },
  { src: "/images/gallery/drapery-install-9.jpg", alt: "Sheer drapery flanked by side panels in dark room", width: 645, height: 1400, categories: ["drapery"] },
  { src: "/images/gallery/shades-install-1.jpg", alt: "White honeycomb shades on living room sliding door", width: 1400, height: 787, categories: ["shades"] },
  { src: "/images/gallery/shades-install-2.jpg", alt: "Dual roller shades over a snowy window view", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-3.jpg", alt: "White panel track shades in a doorway", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-4.jpg", alt: "Honeycomb shades on three windows with fall foliage", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-5.jpg", alt: "Roller shades in a bright living room", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-6.jpg", alt: "Tan honeycomb cellular shade close-up", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-7.jpg", alt: "Woven wood shade in a carved wood window", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-8.jpg", alt: "White roller shade over a home gym window", width: 787, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-9.jpg", alt: "Solar screen panel shades over a patio door", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shutters-install-1.jpg", alt: "Plantation shutters above a sliding door panel shade", width: 869, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shades-install-10.jpg", alt: "Gray roller shade corner detail by a window", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-11.jpg", alt: "Woven wood shades in a bay window with piano", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-12.jpg", alt: "Honeycomb shades in a corner bay window", width: 1400, height: 1050, categories: ["shades"] },
  { src: "/images/gallery/shades-install-13.jpg", alt: "Tan roller shade in an entryway nook", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-14.jpg", alt: "Woven wood roman shades on French doors", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shades-install-15.jpg", alt: "Sheer shading with horizontal vanes close-up", width: 1400, height: 1218, categories: ["shades"] },
  { src: "/images/gallery/shades-install-16.jpg", alt: "Honeycomb shade over an arched bathroom window", width: 1050, height: 1400, categories: ["shades"] },
  { src: "/images/gallery/shutters-install-2.jpg", alt: "White plantation shutters in dim living room", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-3.jpg", alt: "White plantation shutters in bathroom with tub", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-4.jpg", alt: "White bi-fold shutters over closet doors", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-5.jpg", alt: "Arched fan shutters above fireplace windows", width: 1400, height: 932, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-6.jpg", alt: "Wood tone plantation shutters in dining room", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-7.jpg", alt: "White shutter panels on French doors", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-8.jpg", alt: "Magenta plantation shutters in styled room", width: 933, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-9.jpg", alt: "Shutter panels on large sliding glass door", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-10.jpg", alt: "White plantation shutters in bright living room", width: 1400, height: 1051, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-11.jpg", alt: "Shutter window with sheer curtain in bathroom", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-12.jpg", alt: "Close-up of white plantation shutter panels", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-13.jpg", alt: "White shutters wrap around sunroom windows", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-14.jpg", alt: "Arched shutter in navy blue bedroom", width: 787, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-15.jpg", alt: "Triple arched shutters in green sunroom", width: 1400, height: 1347, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-16.jpg", alt: "Close-up of white plantation shutter window", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-17.jpg", alt: "Wood tone shutters in bay window seating area", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-18.jpg", alt: "Cafe-style shutters with curtains in bedroom", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-19.jpg", alt: "Arched shutter above kitchen sink window", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-20.jpg", alt: "Small shutter window above bedroom headboard", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-21.jpg", alt: "Arched shutter above fireplace in vaulted room", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-22.jpg", alt: "Single shutter window in dining room", width: 1400, height: 787, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-23.jpg", alt: "Panoramic view of sunroom plantation shutters", width: 1400, height: 560, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-24.jpg", alt: "Shutter sidelights flanking front entry door", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-25.jpg", alt: "Bi-fold shutters over kids room closet", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-26.jpg", alt: "Installer fitting shutters in a sunroom", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-27.jpg", alt: "Exterior louvered shutters on upper story windows", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-28.jpg", alt: "Tall arched shutter during installation", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-29.jpg", alt: "Half-round top shutters in living room", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-30.jpg", alt: "Black exterior shutters on brick home facade", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-31.jpg", alt: "Bay window wrapped in white plantation shutters", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-32.jpg", alt: "Close-up arched double shutter window", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-33.jpg", alt: "Seven-panel shutters in living room with couch", width: 1400, height: 1050, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-34.jpg", alt: "Shutter panels on double entry doors", width: 1050, height: 1400, categories: ["shutters"] },
  { src: "/images/gallery/shutters-install-35.jpg", alt: "Oval shutter window with blue sky view", width: 1050, height: 1400, categories: ["shutters"] },
];
